spring:
  datasource:
    url: jdbc:mysql://localhost/match-filmes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

jwt:
  secret: ${JWT_SECRET:mysecretkey}
  expiration-time: 3600000
  expiration-time-remember-me: 604800000

env:
  TMDB:
    api_key: ${TMDB_API_KEY}